### ISSUE TITLE
Crash if project contains Popup view.

### ISSUE THREAD

**Issue by suraj-ios** [Survicate/survicate-ios-sdk#1]
Survicate is crash if project contains **XIB** Popup view.

**Comment by shaqonline** [comment]
@suraj-ios I tried to reproduce your issue, but I can't. Could you provide me the details?

**Comment by suraj-ios** [comment]
@shaqonline , Thanks for the response.

I will send you demo project. Please go through the respective demo project and check it.
Steps:-
1. Creating One Demo project, let say **SurvicateTest**
2. Create one **XIB** ViewController.
3. and run the project, it will be crash.(It is happening only in **XIB** NOT any other Popup view like Storyboard inside any Popup view then not at all problem, it is working fine.)


thanks in advance.

**Comment by shaqonline** [comment]
@suraj-ios We just released new version of Survicate iOS SDK. Does your problem still exists?

**Comment by suraj-ios** [comment]
@shaqonline , No issues still exits.

**Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<NSObject 0x280f38120> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key view.'**

**Comment by gierunio** [comment]
@suraj-ios 
Please try with `pod deintegrate` + `pod update`, remove derived data and clean the build folder. Make sure you use 1.0.4 version of the SDK. I tried the sample project you linked above and it is working on my machine.

**Comment by suraj-ios** [comment]
@gierunio 

yaa, its working fine now. Thank a lot.
