### ISSUE TITLE
Objective-C compatibility

### ISSUE THREAD

**Issue by g0rp** [Survicate/survicate-ios-sdk#2]
Hello !

Maybe stupid question or I'm missing something but from your pod I cannot use the Survicate Singleton in an Objective-c file...

As I said, did I missed something ?

What I'm doing in Obj-c file:

`#import <Survicate/Survicate.h>`
or 
`#import <Survicate/Survicate-Swift.h>`

Then I can't reach Survicate class
`[Survicate shared];` or `Survicate.shared` is not available...

I even tried to use:
`@class Survicate;`
or 
`@import Survicate;`

But still nothing... Maybe you have a tip to have access to the SDK with OBJ-C ?
Thanks in advance.

**Comment by j-brzozowski** [comment]
@g0rp could you try new sdk version? `pod 'Survicate', :podspec => 'https://repo.survicate.com/ios/1.0.6/Survicate.podspec'`

**Comment by j-brzozowski** [comment]
Use 1.0.6 version, it should fix problem.
