### ISSUE TITLE
Survey presenting on wrong ViewController

### ISSUE THREAD

**Issue by rfgallagher1** [Survicate/survicate-ios-sdk#5]
The Error: Warning: Attempt to present <Survicate.SurveyViewController: 0x10682d5b0> on <SplashVC: 0x106811dc0> whose view is not in the window hierarchy!

SplashVC is the initial View Controller displayed when launching the app, but it's long gone by the time I fire off the event that should display the Survey. 

Why is it holding on to that old View Controller rather than using whatever's on screen currently, like UIApplication.shared.keyWindow?.visibleViewController

Is there a way to tell Survicate to not use an old VC?

**Comment by rfgallagher1** [comment]
Hey there, do any devs get notified of these?

**Comment by piotr-survicate** [comment]
Hi! 
Sorry for late response, we are already investigating the issue concerning your ViewControllers. Please give us some time to fix the issue, and sorry for the late reply.

**Comment by rfgallagher1** [comment]
Hey guys any update on this? I'm curious why everybody using the SDK isn't experiencing it

**Comment by piotr-survicate** [comment]
Hi!
We have resolved the issue in the newest SDK version: 1.0.8, please check if it works for you.

**Comment by rfgallagher1** [comment]
It works! Great, thanks for the quick turnaround!
