### ISSUE TITLE
XCode 10.2, Swift 5, Module compiled with Swift 4.2 cannot be imported by the Swift 5.0 compiler

### ISSUE THREAD

**Issue by akshitzaveri** [Survicate/survicate-ios-sdk#6]
<img width="1258" alt="Screenshot 2019-04-03 at 14 44 07" src="https://user-images.githubusercontent.com/6559898/55467506-1c488380-561f-11e9-853f-1f33a90f42f9.png">

**Comment by piotr-survicate** [comment]
Hi Trevor!
We are aware of new Xcode version, and right now we are discussing possibilities considering Xcode 10.2 version. It appears, that it would be very tough to support Xcode 10.1 and 10.1 at the same time, so we need to validate, whether branching our SDK to support Xcode 10.1 and 10.2 is something we want to do right now. Please give us some time to settle it, I will come back to you asap :)

**Comment by piotr-survicate** [comment]
Hi!
We are aware of new Xcode version, and right now we are discussing possibilities considering Xcode 10.2 version. It appears, that it would be very tough to support Xcode 10.1 and 10.2 at the same time, so we need to validate, whether branching our SDK to support Xcode 10.1 and 10.2 is something we want to do right now. Please give us some time to settle it, I will come back to you asap :)

**Comment by akshitzaveri** [comment]
Thank you @piotr-survicate 
I suppose branching it out for XCode 10.2 would be the best idea. As the majority of the devs could be on the older version.

**Comment by j-brzozowski** [comment]
@akshitzaveri check out new SDK version - 1.1.0
