### ISSUE TITLE
Compilation error on Xcode 11 beta 7 

### ISSUE THREAD

**Issue by nex-derek** [Survicate/survicate-ios-sdk#7]
Here are the error and some additional information. Please let me know if any more information is needed, thanks!

Error: `Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler: ************/Pods/Survicate/Survicate.framework/Modules/Survicate.swiftmodule/x86_64.swiftmodule`

MacOS version: Mojave 10.14.4 (18E226)
Xcode version: 11.0 beta 7 (11M392r)
Cocoapods version: 1.7.5
Survicate version: 1.1.2

**Comment by akshitzaveri** [comment]
+1

**Comment by j-brzozowski** [comment]
Please try: `pod 'Survicate', :podspec => 'https://repo.survicate.com/ios/1.1.2-swift5.1/Survicate.podspec'`

**Comment by nex-derek** [comment]
Negative, `ld: framework not found Survicate`

**Comment by nex-derek** [comment]
Tried to delete derived data & clean build, but same result

**Comment by j-brzozowski** [comment]
Sorry, typo. `pod 'Survicate', :podspec => 'https://repo.survicate.com/ios/1.1.2_swift5.1/Survicate.podspec'`

**Comment by nex-derek** [comment]
> Sorry, typo. `pod 'Survicate', :podspec => 'https://repo.survicate.com/ios/1.1.2_swift5.1/Survicate.podspec'`

Yep, it works

**Comment by nex-derek** [comment]
@j-brzozowski May I know when will you publish a new version with the fix?

**Comment by j-brzozowski** [comment]
@nex-derek we maintain both versions (for Swift 5.0 and Swift 5.1). We are going to publish 5.1 as soon as final Xcode 11 will be released.

**Comment by racer1988** [comment]
Hi! @j-brzozowski any Eta on the new version now that all is live? 
Thanks

**Comment by matthiaskmt** [comment]
Hi! @j-brzozowski the iOS 13 release is already some days old. Could you give an estimation when the new Survicate release will be live ?

**Comment by j-brzozowski** [comment]
@matthiaskmt - Swift 5.1 update is live (1.1.4).

**Comment by matthiaskmt** [comment]
Awesome, thanks
